### ISSUE TITLE
$validatorProvider is not working for me

### ISSUE THREAD

**Issue by gchokeen** [jpkleemans/angular-validate#13]
I configured the global validation settings as below in app.js and I am loading the controller using loadplugin. Global configuration is not picking up in this case.

Note: Inline configuration of options works

```
app.config(function ($stateProvider, $urlRouterProvider,$validatorProvider){
         $validatorProvider.setDefaults({
            errorElement: 'small',
            errorClass: 'help-block',
        });

        $stateProvider
            .state ('admin', {
                url: '/admin',
                templateUrl: 'views/admin.html',
                controller: 'adminCtrl',
                resolve: {
                    loadPlugin: function($ocLazyLoad) {
                        return $ocLazyLoad.load ([
                            {
                                name: 'vendors',
                                files: [
                                    'vendors/bower_components/autosize/dist/autosize.min.js',
                                    'vendors/bower_components/jquery-validation/dist/jquery.validate.min.js',
                                    'vendors/bower_components/jpkleemans-angular-validate/dist/angular-validate.min.js',

                                    'js/controllers/adminCtrl.js'
                                ]
                            }
                        ])
                    }
                }                
            });


})

```

**Comment by jpkleemans** [comment]
Hi, `$validatorProvider` is only available when `angular-validate.min.js` is loaded.
Because you use lazy loading, the dependency resolver of Angular doesn't know how to inject `$validatorProvider` into your config function.

**Comment by gchokeen** [comment]
I got your point!

I also loading the angular-validate.min.js in index.html. I know lazy loading overriding the config. Is there anyway you can think off to make it work with lazy load. because I am using lazy load all over the project :(

**Comment by jpkleemans** [comment]
If you already load `angular-validate.min.js` and `jquery.validate.min.js` in your index, there's no need to load it again with lazy loading.

**Comment by gchokeen** [comment]
Oh Yes, I removed it and it works well thanks
