### ISSUE TITLE
Validate fields individually

### ISSUE THREAD

**Issue by gaikwad411** [jpkleemans/angular-validate#16]
This validate plugin is great, it really helps to keep the code and logic clean and easy to understand.  

I dont know if this feature is already there, may be it is not documented. But to explain another requirement, we may need to validate fields individually. Now fields are being validated when form gets submitted(all the fields), and there may be requirement to validate a single field on blur, or on particular event. 

I have done a workaround for this, I created a directive for inputs in the form. And on blur event of input I just all "valid" function of validator and it does what I need. 

My query is, is there any existing way to achieve the same, if not it would be nice to have thing.

**Comment by jpkleemans** [comment]
You can use the `onfocusout` option to validate fields on blur:  https://jqueryvalidation.org/validate/#onfocusout

**Comment by gaikwad411** [comment]
Hey Thanks, it was there.
