### ISSUE TITLE
How to include this plugin as independent module

### ISSUE THREAD

**Issue by Toomavic** [jpkleemans/angular-validate#17]
First I have to say thank you for this awesome plugin,
I need to know **# the best practice** of how to integrate this as an independent module 

I am using many custom validate methods, so it would be nice if I separate them from main `angular.module.config`

**Comment by jpkleemans** [comment]
You can add the rules to the config of specific modules: `angular.module('module_name_here').config`

**Comment by Toomavic** [comment]
Greaaaaat Thanks
