### ISSUE TITLE
Validation works after using the input more than 3 time

### ISSUE THREAD

**Issue by Abd-el-hamid** [jpkleemans/angular-validate#18]
I've managed to integrate your libs inside my project. but if I set an input as required I must fill and empty that input multiple times and then the error message appears.
Am I doing something wrong or is it a bug in your project.
I am using angular 1.6.5 and jquery 3.1.1.
regards

**Comment by jpkleemans** [comment]
Have you tried the [onfocusout](https://jqueryvalidation.org/validate/#onfocusout) and [onkeyup](https://jqueryvalidation.org/validate/#onkeyup) options?

**Comment by celicoo** [comment]
@jpkleemans I'm having the same issue, and adding onfocusout and onkeyup is throwing an error. Could you help me, please?

**Comment by jpkleemans** [comment]
@celicoo can you create a jsfiddle (see [demo](http://jsfiddle.net/fdnh3s4L/25/)) to illustrate the problem?
