### ISSUE TITLE
validate() not equal

### ISSUE THREAD

**Issue by bobmulder** [jpkleemans/angular-validate#2]
I just note something - not really important - when using this awesome stuff.

Instead of the `validate()` method of the jQuery validator (http://jqueryvalidation.org/validate), the `validate()` method here can't understand parsed options.

The jQuery validator suggest that the following is possible:

```
$(".selector").validate({
  debug: true
});
```

The `validate()` method of angular-validate can't do that, but options can only parsed via `$scope.validationOptions`. I think it should be mentioned better, or implemented ;)

**Comment by jpkleemans** [comment]
Thanks. I've fixed this in a2822ad

**Comment by bobmulder** [comment]
:+1:
