### ISSUE TITLE
Select ng-model issue

### ISSUE THREAD

**Issue by Cristiian** [jpkleemans/angular-validate#21]
Hello, I got working this wrapper in my application, but I found out that when you set a ng-model value in a select, the validation just stops working, I don't know if this is an angular issue or the wrapper, or jquery validate.

[JSFiddle example](https://jsfiddle.net/yee1gp0z/5/)

**Comment by jpkleemans** [comment]
In your example `user` is undefined, so angular generates the following `<option>` in your `<select>`:

```html
<option value="? undefined:undefined ?" selected="selected"></option>
```

jQuery Validate thinks this is valid, because "? undefined:undefined ?" is a valid 'required' value. Only if the value is not set (`value=""`), the validator will mark it as invalid.
