### ISSUE TITLE
Unable to validate multiple email with input type email

### ISSUE THREAD

**Issue by HarsharanSingh007** [jpkleemans/angular-validate#24]
Hi
Am trying to validate multiple email address but it's not accepting the external method what I've got from doing the research. 
Ref: http://jsfiddle.net/leniel/xFphm/7/

```
$validatorProvider.addMethod("multiemail", function (value, element) {
		if (this.optional(element)) {
			return true;
		}
		
		var emails = value.split(/[" "]+/); // spliting the email using space
		console.log(emails);
		valid = true;
		for (var i in emails) {
			value = emails[i];
			valid = valid && $validatorProvider.email.call(this, $.trim(value), element);
		}
		return valid;
	}, "Invalid Email address");
```
If I'll use the single email address then it will throw the below error:
![screenshot_10](https://user-images.githubusercontent.com/23027414/36256509-532f5b84-1279-11e8-86ae-5fe22e04df7b.png)

If I'll add the multiple email address then it will throw the normal email validation error:
![screenshot_11](https://user-images.githubusercontent.com/23027414/36256578-8ed912d8-1279-11e8-9364-1818d47faba3.png)

Please Help to resolve the issue/bug asap.
Thanks in advance

**Comment by jpkleemans** [comment]
Hi, `$validatorProvider.email` does not exist. You can use the method from jQuery validate directly: `jQuery.validator.methods.email` (or `$.validator.methods.email`).
