### ISSUE TITLE
errorPlacement funcion being called multiple times

### ISSUE THREAD

**Issue by nfabian13** [jpkleemans/angular-validate#4]
Hello,

I have set up my validation options in my controller like this:

```
$scope.validationOptions = {
          rules:{
            clientcode: "required",
            username: "required",
            password: "required"
          },
          errorPlacement: function(err, element){
            console.log(err);
          }
        };
```

And when I see the browser console i see printed 3 times the following:

```
[label#clientcode-error.error]
[label#clientcode-error.error]
[label#clientcode-error.error]
```

I need to solve this since I want to place my errors within a div container like a bullet list at the top of my HTML form with the erros sumary but I cannot do it because I will have the same error repeated 3 times for each field.

any idea how to avoid this function being called multiple times?

**Comment by jpkleemans** [comment]
Hi,

I've fixed this. Can you test if it works?

Thanks for reporting!
