### ISSUE TITLE
$validatorProvider is undefined

### ISSUE THREAD

**Issue by vafrcor** [jpkleemans/angular-validate#5]
Requirement:
- Angular 1.3.20
- jpkleemans-angular-validate 1.0.0

Case: while i tried to set default to jQuery Validate on Angular application config, it show this error

``` javascript
Error: [$injector:modulerr] Failed to instantiate module application due to:
$validatorProvider is undefined
...
```

Any solution?

**Comment by vafrcor** [comment]
solved, my bad.
I'm really sorry.

**Comment by jpkleemans** [comment]
@vafrcor no problem! Glad you've fixed it.
