### ISSUE TITLE
TypeError: c.validate is not a function

### ISSUE THREAD

**Issue by rohitbind** [jpkleemans/angular-validate#6]
TypeError: c.validate is not a function

**Comment by jpkleemans** [comment]
Hi,

Are you sure you've loaded all scripts (in the correct order) in your html?

``` html
<!-- jQuery scripts -->
<script src="path/to/jquery.min.js"></script>
<script src="path/to/jquery.validate.min.js"></script>

<!-- Angular scripts -->
<script src="path/to/angular.min.js"></script>
<script src="path/to/angular-validate.min.js"></script>
```

**Comment by rohitbind** [comment]
I am using grunt to concat and make a single file for all dependency.

**Comment by jpkleemans** [comment]
Can you make sure Grunt concats the files in the correct order? It's important that the jquery files are loaded before angular.

**Comment by rohitbind** [comment]
yup sure I will do that and update here the same. Thanks for the support :+1:
