### ISSUE TITLE
$validatorProvider.format is not a function

### ISSUE THREAD

**Issue by jaybayley** [jpkleemans/angular-validate#9]
Hi there,

I'm using your plugin via Bower, and getting the above error when trying to `setDefaultMessages`. Looking at the src and dist files in your repo vs what Bower installs, I can see that the `format` method is indeed missing in the bower version.

How can I resolve this?

Cheers,

Jay

**Comment by jpkleemans** [comment]
Hi,

I'm sorry, I forgot to release that feature (#8).
I just released version 1.1.0, which should fix your error.

Thanks!

JP
